theme: jekyll-theme-cayman
title: "Rain Flower"
description: Personal AI-curated daily digest
baseurl: "/rain-flower"
url: "https://izayoi-arashi.github.io"

# Build settings
markdown: kramdown
future: true
plugins:
  - jekyll-feed
feed:
  path: feed.xml
exclude:
  - ".github"
  - "node_modules"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
